"""Block-based perfect maze generated by recursive backtracker."""

from __future__ import annotations

import random
from typing import List, Optional

from .cell import Cell


class Maze:
    """
    Every square is either OPEN or WALL.
    Grid dimensions are always odd (2*cells_wide+1 by 2*cells_high+1) so that
    every logical room is separated from its neighbours by a wall square.
    """

    def __init__(
        self,
        cells_wide: int,
        cells_high: int,
        rng: Optional[random.Random] = None,
    ) -> None:
        self.cols = cells_wide * 2 + 1
        self.rows = cells_high * 2 + 1
        self.wall: List[List[bool]] = [
            [True] * self.cols for _ in range(self.rows)
        ]
        rng = rng or random.Random()
        self._carve(rng, cells_wide, cells_high)
        self.start = Cell(1, 1)
        self.goal = Cell(self.rows - 2, self.cols - 2)

    def _carve(self, rng: random.Random, cells_wide: int, cells_high: int) -> None:
        visited = [[False] * cells_wide for _ in range(cells_high)]
        stack: List[tuple[int, int]] = []
        start_r, start_c = 0, 0
        visited[start_r][start_c] = True
        self.wall[start_r * 2 + 1][start_c * 2 + 1] = False
        stack.append((start_r, start_c))

        dirs = [(-1, 0), (1, 0), (0, -1), (0, 1)]

        while stack:
            cur_r, cur_c = stack[-1]
            candidates: List[tuple[int, int, int, int]] = []
            for dr, dc in dirs:
                nr, nc = cur_r + dr, cur_c + dc
                if (
                    0 <= nr < cells_high
                    and 0 <= nc < cells_wide
                    and not visited[nr][nc]
                ):
                    candidates.append((nr, nc, dr, dc))
            if not candidates:
                stack.pop()
                continue
            nr, nc, dr, dc = candidates[rng.randrange(len(candidates))]
            wall_row = cur_r * 2 + 1 + dr
            wall_col = cur_c * 2 + 1 + dc
            self.wall[wall_row][wall_col] = False
            self.wall[nr * 2 + 1][nc * 2 + 1] = False
            visited[nr][nc] = True
            stack.append((nr, nc))

    def is_open(self, row: int, col: int) -> bool:
        if row < 0 or row >= self.rows or col < 0 or col >= self.cols:
            return False
        return not self.wall[row][col]

    def is_open_cell(self, cell: Cell) -> bool:
        return self.is_open(cell.row, cell.col)
